// Mocks generated by Mockito 5.4.2 from annotations
// in task_manager_app/test/auth/auth_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:task_manager_app/core/model/user_info.dart' as _i2;
import 'package:task_manager_app/features/auth/models/login_request_model.dart'
    as _i5;

import 'auth_service_test.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUserInfo_0 extends _i1.SmartFake implements _i2.UserInfo {
  _FakeUserInfo_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthServiceTest].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthServiceTest extends _i1.Mock implements _i3.AuthServiceTest {
  MockAuthServiceTest() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.UserInfo> login(_i5.LoginRequestModel? loginRequestModel) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [loginRequestModel],
        ),
        returnValue: _i4.Future<_i2.UserInfo>.value(_FakeUserInfo_0(
          this,
          Invocation.method(
            #login,
            [loginRequestModel],
          ),
        )),
      ) as _i4.Future<_i2.UserInfo>);
}
